/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminLayoutFooter: typeof import('./components/admin/LayoutFooter.vue')['default']
    AdminLayoutHeader: typeof import('./components/admin/LayoutHeader.vue')['default']
    AdminLayoutSider: typeof import('./components/admin/LayoutSider.vue')['default']
    CommonCalendar: typeof import('./components/common/Calendar/index.vue')['default']
    CommonCalendarEvent: typeof import('./components/common/Calendar/Event.vue')['default']
    CommonCodeAI: typeof import('./components/common/CodeAI.vue')['default']
    CommonCodeMirrorCodeMirror: typeof import('./components/common/CodeMirror/CodeMirror.vue')['default']
    CommonPageHeader: typeof import('./components/common/PageHeader.vue')['default']
    CommonRadio: typeof import('./components/common/Radio.vue')['default']
    CommonTheWindow: typeof import('./components/common/TheWindow.vue')['default']
    HeroSlider: typeof import('./components/HeroSlider.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    ThisForTest: typeof import('./components/ThisForTest.vue')['default']
    UseElementVisibility: typeof import('@vueuse/components')['UseElementVisibility']
    UseImage: typeof import('@vueuse/components')['UseImage']
    UseVirtualList: typeof import('@vueuse/components')['UseVirtualList']
  }
}
