/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb']
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADatePicker: typeof import('@arco-design/web-vue')['DatePicker']
    AdminLayoutFooter: typeof import('./components/admin/LayoutFooter.vue')['default']
    AdminLayoutHeader: typeof import('./components/admin/LayoutHeader.vue')['default']
    AdminLayoutSider: typeof import('./components/admin/LayoutSider.vue')['default']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    ATrigger: typeof import('@arco-design/web-vue')['Trigger']
    HeroSlider: typeof import('./components/HeroSlider.vue')['default']
    IconApps: typeof import('@arco-design/web-vue/es/icon')['IconApps']
    IconBug: typeof import('@arco-design/web-vue/es/icon')['IconBug']
    IconBulb: typeof import('@arco-design/web-vue/es/icon')['IconBulb']
    IconCalendar: typeof import('@arco-design/web-vue/es/icon')['IconCalendar']
    IconClose: typeof import('@arco-design/web-vue/es/icon')['IconClose']
    IconDragArrow: typeof import('@arco-design/web-vue/es/icon')['IconDragArrow']
    IconHome: typeof import('@arco-design/web-vue/es/icon')['IconHome']
    IconMessage: typeof import('@arco-design/web-vue/es/icon')['IconMessage']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    ThisForTest: typeof import('./components/ThisForTest.vue')['default']
    UseImage: typeof import('@vueuse/components')['UseImage']
  }
}
